[workspace]
resolver = "2"
members = [
    "hello_world",
    "count",
    "fizzbuzz"
, "number", "arithmetic-operations-quiz","simple-poker"]
exclude = [
    "target"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
